### ISSUE TITLE
Replace all int timeouts with TimeSpan

### ISSUE THREAD

**Issue by tomaustin700** [Streets-Heaver/SHAutomation#14]
**Is your feature request related to a problem? Please describe.**
Currently a ms int is used to set timeouts, this can make it hard to know what is actually being set (ms, s, mins, etc). 

**Describe the solution you'd like**
Change all timeouts to be TimeSpan instead of int.

**Additional context**
This would be a breaking change so version number would have to jump accordingly.

**Comment by tomaustin700** [comment]
This is probably made more complicated because TimeSpans can't be given default values in method signatures. Need to think what we do with that, ideally I'd like to remove all TimeSpan default parameters and instead use overloaded methods however that is a huge change. @ThomasPoucher thoughts on this?

**Comment by ThomasPoucher** [comment]
@tomaustin700 Yeah I can't think of another way and think it'd be beneficial for anyone who uses this package in case they need larger timeouts for their applications. It's also not explained by the current parameter names that any of the current timeouts use milliseconds whereas timespan can be whatever the user wants.
