### ISSUE TITLE
Using a Parent in a find expression that is no longer available throws no error

### ISSUE THREAD

**Issue by tomaustin700** [Streets-Heaver/SHAutomation#30]
**Describe the bug**
If you're calling `Find` and passing in a parent like this:
```csharp
Find(x => x.ByClassName(ClassNameConstants.SpinEdit), parent: staleElement).IsEnabled.Should().BeFalse();
```
and the parent is no longer available no exception is thrown and the `Find` will fail

**To Reproduce**
Assign a element to a variable, change the UI so that the element is no longer on screen, use the element variable as a parent in a find expression.

**Expected behavior**
Exception should be thrown to let user know parent element is not available

**Comment by tomaustin700** [comment]
Probably just wants to throw `ElementNotFoundException` in this case.

**Comment by ThomasPoucher** [comment]
Some other options on implementation.

- Automation current property may error see here https://docs.microsoft.com/en-us/dotnet/api/system.windows.automation.automationelement.current?view=net-5.0

- If parent does end up being cached, SHInspect attempts to get the xpath out again causing an error when it no longer exists, so thats a backup option

**Comment by tomaustin700** [comment]
Need to think of the best way to detect that `parent` is no longer available. Currently we don't have access to `Current` so may need to look at that first.

**Comment by tomaustin700** [comment]
#38 Enables this to move forward now.
