### ISSUE TITLE
Exists timeout does not use the timeout specified if the visual tree search is longer than the timeout

### ISSUE THREAD

**Issue by ThomasPoucher** [Streets-Heaver/SHAutomation#43]
**Describe the bug**
If you pass a timeout of 0.5seconds and it takes 50 seconds to search the tree, the exists will last for 50 seconds. 

**Expected behavior**
Should only allow 0.5 seconds for searching if 0.5 seconds is specified

**Additional context**
This is down to the transaction timeouts

**Comment by tomaustin700** [comment]
Will try and address in 5.0.0 on #63
